nicow991/no_cash

app/controllers/offers_controller.rb

- added Crud actions to the Offer controller

Offer for CRUD

---

app/controllers/items_controller.rb

CRUD methods for Items is done includin my_items

CRUD of Items is done for fist go

---

app/controllers/deals_controller.rb
app/controllers/reviews_controller.rb
db/migrate/20240319151634_add_content_to_reviews.rb
db/schema.rb

method create for reviews is done, also I modified the shceema, I added a new column for content, since there were done.
we might need to add another column for reviews since we dont have points for it (I.E. 1 to 5)

create method for reviews is done

---

app/controllers/deals_controller.rb
app/views/deals/_deals.html.erb
app/views/deals/index.html.erb
app/views/layouts/application.html.erb
db/schema.rb

-added a container to the application.html
-fixed logic in deals#index to show my deals
-created partial _deals
_ created basic view for deals index

Deals index

---

app/controllers/items_controller.rb
app/controllers/pages_controller.rb
app/views/items/_form.html.erb
app/views/items/new.html.erb

form is done (cloudinary part is commented and also one other line is commented that we will need in the future

form for new Item is done (partial)

---

app/models/category.rb
app/models/deal.rb
app/models/item.rb
app/models/offer.rb
app/models/review.rb
app/models/user.rb
app/views/items/_form.html.erb

validations are done need work with chatroom and co.

Validations

---

.gitignore
Gemfile
Gemfile.lock
app/views/items/_card.html.erb
app/views/items/_form.html.erb
app/views/items/index.html.erb
config/environments/development.rb
config/storage.yml
db/migrate/20240319181857_create_active_storage_tables.active_storage.rb
db/schema.rb

cloudinary is already set guys need to bundle and migrate

Cloudinary

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/controllers/offers_controller.rb
app/models/category.rb
app/models/item.rb
app/models/preference.rb
app/views/items/show.html.erb
app/views/layouts/application.html.erb
app/views/offers/new.html.erb
db/migrate/20240320141624_create_preferences.rb
db/schema.rb
db/seeds.rb
test/models/preference_test.rb

- fixed logic in items controller
- created the view for items#show
- created a new table preferences for items/categories
- created preferences seed

Items show

---

db/seeds.rb

seeds fixed and uncommented. I maaaay have reduced the amount of users cause it was taking too long. If you dont feel like merging this you should still add an 'address' to items in the seed

seeds fixed and uncommented.

---

app/controllers/deals_controller.rb
app/controllers/offers_controller.rb
app/models/deal.rb
app/models/item.rb
app/models/offer.rb
app/models/user.rb
app/views/deals/_deals.html.erb
app/views/deals/index.html.erb
app/views/items/_offer.html.erb
db/migrate/20240318195816_create_offers.rb
db/migrate/20240319195034_add_user_to_offers.rb
db/migrate/20240320221834_add_user_to_deals.rb
db/migrate/20240321161632_create_items_offers.rb
db/schema.rb
db/seeds.rb
test/models/offered_item_test.rb

- changed offers table so it only contains item_id for the offered item
- added hidden join table items_offers 
- now we can access:
user.my_offers, user.received_offers (we cannot edit these for... reasons. we'd need to modify the table for that and im just not feeling it rn)
and we can access and edit:
item.offer -> sent offer
item.offers -> received offers
offer.deal = Deal.new to create a deal
item.offer = Offer.new to create an offer
item2.offers << item.offer to connect offers
item.user

Associate deal users

---

app/controllers/chatrooms_controller.rb
app/models/chatroom.rb
app/views/chatrooms/_chats.html.erb
app/views/chatrooms/index.html.erb
app/views/shared/navbar/_avatar.html.erb
config/routes.rb
db/seeds.rb

- navbar: change chats to Inbox
- added the route to chatroom index
- created the index in the chatroom controller and added the logic
- created the chatroom index.html.erb view, as well as a chats partial to render it
- improved the seeds for chatrooms (2 participants, 2 messages for each chatroom)

Chatrooms index

---

app/views/items/show.html.erb

added the button and the color to it.

added chat button to the items show

---

app/views/chatrooms/_chats.html.erb
app/views/chatrooms/show.html.erb
app/views/messages/_message.html.erb

improved the show view. The current user's messages have a different bg color and go to the end of the div. 
UX-> easier to follow and differentiate my messages from the ones I receive

Chatroom show

---

app/controllers/users_controller.rb
app/models/user.rb
app/views/devise/registrations/edit.html.erb
app/views/shared/navbar/_avatar.html.erb
app/views/users/show.html.erb
config/routes.rb
db/migrate/20240322183927_remove_item_to_preferences.rb
db/migrate/20240322184159_add_address_to_items.rb
db/schema.rb
test/controllers/users_controller_test.rb

'created routes, views and controller to have a profile page. 
added two migrations to the db. Address to items, and preferences changed item to user

User profile

---

app/views/items/_card.html.erb
app/views/items/index.html.erb
db/schema.rb

changed the backgroung color, the grid display now 4 cards per row, and changed the max & min heights so the cards keep always the same size , and fixed the picture size

a little style to the item index

---

db/seeds.rb

fixed the seeds, now they work.
As we changed the schema of the db, the seeds needed to be adapted.
Also, I set the categories, preferences and condition of the goods to Spanish as the intended market

seeds working now

---

db/seeds.rb

changed conditions to match what we currently have in the forms

changed conditions to match what we currently have in the forms

---

app/controllers/chatrooms_controller.rb
app/controllers/items_controller.rb
app/models/chatroom.rb
app/models/user.rb
app/views/chatrooms/_chats.html.erb
app/views/items/show.html.erb
app/views/shared/_footer.html.erb

- fixed footer chats button so it redirects to chatrooms_path
- added chat create action and made necessary changes to chat creation button
- improved _chats so its simpler and less error prone using chatroom.users and the safe navigation operator.

Chatbuttonsfix

---

app/assets/stylesheets/application.scss
app/views/items/_card.html.erb

changed the carousel height, changed the max and min hight of the titles, created font sizes classes in the scss, added address to the card, changed the paddings of the card, titles and button

Item index style

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/chatrooms_controller.rb
app/controllers/deals_controller.rb
app/controllers/items_controller.rb
app/controllers/offers_controller.rb
app/policies/application_policy.rb
app/policies/chatroom_policy.rb
app/policies/deal_policy.rb
app/policies/offer_policy.rb
db/migrate/20240325143128_add_admin_to_users.rb
db/schema.rb
test/policies/chatroom_policy_test.rb
test/policies/deal_policy_test.rb
test/policies/offer_policy_test.rb

pundit works 
-if you are not an integrant of the chat you're unable to access the chat
-If you're not in the offer or deal you cant do anything

pundit for chat offers and deals

---

app/views/items/_card.html.erb

button centered with a div class

button card in the index was centered

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/pages/_home.scss
app/views/items/show.html.erb
app/views/layouts/application.html.erb
app/views/offers/_form.html.erb
app/views/shared/_footer.html.erb

- added bootstrap variables primary, secondary, primary-dark, secondary-dark, primary-darker, secondary-marker, primary-light, secondary-light
- improved item show style for mobile

Item show style overhaul

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_footer.scss
app/views/shared/_navbar.html.erb

made nav sticky and put footer at bottom

Footer nav stickyness

---

app/assets/stylesheets/pages/_home.scss
app/views/items/my_items.html.erb
app/views/shared/_footer.html.erb
app/views/shared/navbar/_avatar.html.erb

- added an option to create products in Mis productos
- added logic in the navbar and footer(when app) to display a bell if the user has offers with pending reply

Misproductos crear

---

app/assets/stylesheets/config/_bootstrap_variables.scss
app/views/items/_card.html.erb
app/views/items/_form.html.erb
app/views/items/index.html.erb
app/views/items/show.html.erb
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb

changed the primry color to a colder one and put the correct backgroung code for the forms in html

changed pallet color and fixed composition in the forms

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/views/shared/_footer.html.erb

changed footer & navbar height in the variables

changed footer navbar height

---

app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb

- footer now  stays at bottom of page always

fixed footer not staying at bottom for desktop

---

app/views/deals/_accepted_deals.html.erb
app/views/deals/_cancelled_deals.html.erb
app/views/deals/_completed_deals.html.erb
app/views/deals/_received_offers.html.erb
app/views/deals/_sent_offers.html.erb
app/views/deals/index.html.erb
app/views/pages/home.html.erb

& changed some h1 repeated in a single view in deals_index and home

make more uniform the titles in deals index 

---

app/controllers/preferences_controller.rb
app/controllers/users_controller.rb
app/models/preference.rb
app/views/users/show.html.erb
config/routes.rb
test/controllers/preferences_controller_test.rb

Preferences

---

app/views/items/show.html.erb

changed the border radious of the button

Deals style

---

app/views/items/show.html.erb

same changes of last pull r. but only in the item show

item show style

---

app/assets/stylesheets/config/_fonts.scss
app/javascript/controllers/index.js
app/views/devise/registrations/new.html.erb
app/views/users/show.html.erb

fixed bugs with perfil, if there is no image will not brake

Perfil fix

---

app/controllers/items_controller.rb
app/views/deals/_show_reviews.html.erb
app/views/items/show.html.erb

added reviwes to the items show, edited the style of the whole show and buttons

Reviews item show

---

app/views/items/show.html.erb
app/views/shared/navbar/_avatar.html.erb

changed the logo for an icon in the nav(menu)bar

navbar icon

---

app/views/deals/show.html.erb
app/views/items/_chatroom.html.erb
app/views/offers/show.html.erb

changed all the message icons for: enviar mensaje, button. And now the ver perfil button is working in offers, deals and items show, instead of reviews button.  
All the new buttons are redirecting well.

Icons for message

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/controllers/items_controller.rb
app/views/devise/registrations/edit.html.erb
app/views/items/index.html.erb
app/views/items/my_items.html.erb
app/views/shared/_banner.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb
app/views/users/profile.html.erb

- fixed edit user that was broken.
- fixed bug when rendering the items index due to user's preferences and recommendations (see items controller current user && current_user.preferences.any?
- style: created a shared banner, changed bg colours to grey and turquoise for text.

Fix edit user

---

app/assets/stylesheets/pages/_home.scss
app/views/chatrooms/_chats.html.erb
app/views/items/_card.html.erb
app/views/items/_my_items.html.erb
app/views/items/_preferences.html.erb
app/views/items/_recommendations.html.erb
app/views/items/index.html.erb
app/views/items/my_items.html.erb
app/views/messages/_message.html.erb
app/views/users/profile.html.erb
app/views/users/show.html.erb

- chats order chronologically
- you translated in show chat
- categories on top of imgs in cards
- changed my items profile and show to display cards

Fix chats and other cool stuff too

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/views/users/profile.html.erb

buttons are a little better

---

app/views/items/show.html.erb
db/schema.rb

I also added some style to the category button, margin to the fliud container etc.

created a div row class to display the picture at the right side

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

Fixed arrow by creating a new class which assigns the gray color to the section of the nav that needs to have a background color

fixed nav background, now the arrow is not within the nav background but outside it

---

app/views/items/show.html.erb

made responsive the categories of the item show (the whole show is responsive now)

categories responsive

---

db/seeds.rb

fixed the seed so no repeated chats are created when running db:seed

fixed seed so no repeated chats are created

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_footer.scss
app/views/chatrooms/show.html.erb
app/views/deals/_show_reviews.html.erb
app/views/deals/_status_item.html.erb
app/views/deals/index.html.erb
app/views/deals/show.html.erb
app/views/items/show.html.erb
app/views/messages/_message.html.erb
app/views/offers/show.html.erb
app/views/pages/home.html.erb
app/views/shared/_banner.html.erb
app/views/shared/_footer.html.erb
app/views/users/profile.html.erb
app/views/users/show.html.erb
db/seeds.rb

-removed redundant banner logo 
-changed footer background color from transparent to white
-changed button hover color from gray to light blue
-changed user.email to user.nickname everywhere

Lastminutefixes

---

app/assets/stylesheets/application.scss
app/views/deals/index.html.erb
app/views/offers/show.html.erb

- mis trueques is centered
- fixed mi perfil button in offer show

corrected centering of mistrueques

---

app/assets/stylesheets/components/_banner.scss
app/views/shared/_banner.html.erb

banner image now showing in production!

Fixedbannerimg

---

app/assets/stylesheets/application.scss
app/controllers/items_controller.rb
app/controllers/users_controller.rb
app/views/devise/registrations/new.html.erb
app/views/users/profile.html.erb
app/views/users/show.html.erb

-fixed logic to hide deleted products in both profile and users show.
- passing the correct info from the item controller.
- redirect to profile when deleting an item

Fix item delete

---

app/assets/stylesheets/application.scss
app/views/deals/show.html.erb
app/views/offers/show.html.erb

edited the buttons (offers and deals view) in the html file, in a new branch. you can also find now the style in the right file. The product is the same as before, but with better practices :) - thanks

Views d and o

---

app/assets/stylesheets/application.scss
app/controllers/items_controller.rb
app/views/items/index.html.erb

- changed the background color of the check categories boxes - in the sign up view
-  check if a search has been performed in the index method of ItemsController
- refactored the  index to display recommendations and preferences based on search status (showing only search results after searches)

Categories check

---

app/assets/stylesheets/application.scss
app/views/deals/_cancel_offer.html.erb
app/views/offers/show.html.erb

- in offers show: deleted an extra div in the buttons, deleted margin top (my2) to the danger button and changed the button reviews for the ver perfil button
- in dels show: changes in the cancel button (my2) are also reflected here"
- app.scss: added custom font size to the buttons

Offers show b

---

app/assets/stylesheets/application.scss
app/views/devise/sessions/new.html.erb
app/views/pages/home.html.erb
config/initializers/devise.rb

- devise: enabled email configuration to send password reset emails
- sesions: added reset password option to the login
- app scss: added style to btn -forgot password-
- home: Added meta tags for Open Graph properties in the home
I think these are the last changes for the app to work properly. Thank you!!

Reset password
